experiment:
    name: Dummy experiment
    description:
        Describing what the experiment is about and what the experimenter
        aims to achieve.
    workdir: /home/phil/workspace/divvy2.0/
    fixed:
        a: 0.1
        b: 20.0
        c: "ABC"
    comparison:
        params:
          x: [0.01, 0.1, 1.0, 10.0]
        optimised:
            optimiser: "GridSearch"
            opt_params:
                gridRes: 10
            params:
                d: [1,2]
                y: linear(0, 3.14)
                z: logscale(1, 10)
            commands:
                - python example/dummyExperiment.py ${x} ${y} ${z}
        repeat: 10
    workers: 3
