experiment:
    name: Dummy experiment
    description:
        Describing what the experiment is about and what the experimenter
        aims to achieve.
    options:
        outdir: /tmp
        workdir: /home/phil/workspace/sandbox/divvy/
    replacements:
        param1: 0.2
        param2: [1,2,3,4]
        param3: "hello world" #[0.0, 2.0]
    repeat: 5
    cpus: 3
    commands:
        - python example/dummyExperiment.py ${param1} ${param2} ${param3}
