experiment:
    name: Dummy experiment
    description:
        Describing what the experiment is about and what the experimenter
        aims to achieve.
    options:
        outdir: /path/to/data/dir/
        workdir: /path/to/your/project
    replacements:
        param1: 0.2
    repeat: 10
    cpus: 3
    commands:
        - python example/dummyExperiment.py ${param1}
